# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda36ee6ce2d9c6c5b776520eeffb7735f3168dde6ede181db043af594472b21fb36274074a6709eab959c2bc34c63e0e90e7ca3d6580b8cce14c70bd9a556d9

test:
  secret_key_base: ff749c72283ebcae70e2cdd3102ae89b9be673fa1170bf8836346f7f4ed1cde2dcd1391a67f8ee5415d21e0012c9812014f7803398468bef642247db5ddcbc9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
